# Generated by Django 3.1 on 2023-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_auto_20230621_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empaneled_Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='general_listing')),
                ('company_profile', models.ImageField(blank=True, upload_to='general_listing')),
                ('small_video', models.ImageField(blank=True, upload_to='general_listing')),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(choices=[('yarn', 'yarn'), ('fabric', 'fabric'), ('garment', 'garment'), ('home', 'home'), ('others', 'others')], max_length=15)),
                ('kind_of_products', models.CharField(blank=True, max_length=1000)),
                ('company_website', models.CharField(blank=True, max_length=100)),
                ('company_address', models.CharField(blank=True, max_length=500)),
                ('information', models.CharField(blank=True, max_length=1000)),
                ('name_of_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='General_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_address', models.CharField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='company_profile',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='small_video',
        ),
    ]
