# Generated by Django 3.1 on 2023-06-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_auto_20230622_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empaneled_vendor',
            name='image',
        ),
        migrations.AddField(
            model_name='empaneled_vendor',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='Empaneled_Vendor'),
        ),
        migrations.AlterField(
            model_name='empaneled_vendor',
            name='company_profile',
            field=models.ImageField(blank=True, upload_to='Empaneled_Vendor'),
        ),
        migrations.AlterField(
            model_name='empaneled_vendor',
            name='small_video',
            field=models.ImageField(blank=True, upload_to='Empaneled_Vendor'),
        ),
    ]
